Repository Jobs-Js/JJA, pull requests merged in 2023-09, with the labels that each got.

#14 🎨 style: header 마크업 및 기능 구현
  .babelrc
  package.json
  src/assets/images/JJA.svg
  src/assets/images/github.svg
  src/components/Header/Header.jsx
  src/pages/RootLayout.jsx
  webpack.config.js
  yarn.lock
Labels: ✨기능 추가, 🎨HTML/CSS

#10 ⚙️ config: 이모션, 폰트 재설정
  .babelrc
  src/App.js
  src/style/fonts.css
  src/style/globalStyle.js
  src/style/theme.js
  yarn.lock
Labels: 🐞버그 수정, ⚙️설정

#11 🎨 style: home (목록) 페이지 마크업
  package-lock.json
  package.json
  public/img/cover/cover10.png
  public/img/cover/cover11.png
  public/img/cover/cover12.png
  public/img/cover/cover2.png
  public/img/cover/cover4.png
  public/img/cover/cover5.png
  public/img/cover/cover6.png
  public/img/cover/cover7.png
  public/img/cover/cover9.png
  public/img/spine/spine10.png
  public/img/spine/spine11.png
  public/img/spine/spine12.png
  public/img/spine/spine2.png
  public/img/spine/spine4.png
  public/img/spine/spine5.png
  public/img/spine/spine6.png
  public/img/spine/spine7.png
  public/img/spine/spine9.png
  src/assets/images/bookShelf.png
  src/db/data.json
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPageStyle.jsx
  webpack.config.js
Labels: 🎨HTML/CSS

#18 🎨 style: 책 목차 페이지 (IndexPage) 마크업 및 기능 구현
  package-lock.json
  package.json
  src/assets/images/arrow-circle.svg
  src/components/ArrowButton/ArrowButton.jsx
  src/db/chapter.json
  src/db/data.json
  src/pages/BookcontentsPage/IndexPage/IndexPage.jsx
  src/pages/BookcontentsPage/IndexPage/IndexPageStyle.jsx
  src/pages/MainPage/MainPage.jsx
  src/style/globalStyle.js
  webpack.config.js
  yarn.lock
Labels: ✨기능 추가, ⚙️설정, 🎨HTML/CSS

#20 🐛 fix: url 전달이 안되는 문제 해결
  src/pages/MainPage/MainPage.jsx
Labels: 🐞버그 수정

#23 📝 docs: json 데이터 추가
  src/db/content.json
  src/db/pptImg.json
Labels: 📜문서

#24 🎨 style: info 페이지 마크업
  src/components/Header/Header.jsx
  src/pages/InformationPage/InformationPage.jsx
Labels: 🎨HTML/CSS
