Repository Jobs-Js/JJA, pull requests merged in 2023-10, with the labels that each got.

#17 ✨ feat: 책 속지 페이지 마크업 및 기능 구현
  package.json
  src/assets/images/arrow-left-circle.svg
  src/assets/images/arrow-right-circle.svg
  src/assets/images/menu-circle.svg
  src/components/CircleButton/CircleButton.jsx
  src/db/chapter.json
  src/db/content.json
  src/db/pptImg.json
  src/pages/BookcontentsPage/ChapterPage/ChapterPage.jsx
  src/pages/BookcontentsPage/ChapterPage/ChapterPageStyle.jsx
  webpack.config.js
  yarn.lock
Labels: ✨기능 추가, ⚙️설정, 🎨HTML/CSS

#29 🎨 style: 모바일 버전 info 페이지 마크업
  src/components/Header/Header.jsx
  src/pages/InformationPage/InformationPage.jsx
Labels: 🎨HTML/CSS

#32 ✨ feat: 이미지 로딩 시에 spinner 구현
  src/assets/images/spinner.svg
  src/components/Spinner/Spinner.jsx
  src/pages/BookcontentsPage/ChapterPage/ChapterPage.jsx
  src/pages/BookcontentsPage/ChapterPage/ChapterPageStyle.jsx
Labels: ✨기능 추가, ♻️리팩토링

#35 🐛 fix: 배경이미지가 load안되는 문제 해결
  webpack.config.js
Labels: 🐞버그 수정

#36 🎨 style: 모바일 버전 홈 페이지 마크업
  src/pages/MainPage/MainPageStyle.jsx
Labels: 🎨HTML/CSS

#39 🎨 style: header infopage 반응형 분기 수정
  src/components/Header/Header.jsx
  src/pages/InformationPage/InformationPage.jsx
Labels: 🎨HTML/CSS

#40 🎨 style: 모바일 버전 chapter 페이지
  package.json
  src/components/CircleButton/CircleButton.jsx
  src/db/content.json
  src/pages/BookcontentsPage/ChapterPage/ChapterPage.jsx
  src/pages/BookcontentsPage/ChapterPage/ChapterPageStyle.jsx
  src/pages/BookcontentsPage/IndexPage/IndexPageStyle.jsx
  src/utils/debounce.js
  yarn.lock
Labels: ✨기능 추가, 🎨HTML/CSS

#46 🐛 fix: 책 회전시 표지 이미지 Load가 애니메이팅 이후되는 문제 해결
  src/pages/BookcontentsPage/IndexPage/IndexPage.jsx
  src/pages/BookcontentsPage/IndexPage/IndexPageStyle.jsx
Labels: 🐞버그 수정

#43 🎨 style: 파비콘 등록
  package-lock.json
  public/favicon.ico
  public/index.html
  webpack.config.js
  yarn.lock
Labels: 🎨HTML/CSS

#45 📝 docs: readme 작성
  README.md
Labels: 📜문서
